apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: welcome
  name: welcome-route
  namespace: rh1-welcome
spec:
  port:
    targetPort: 8888-tcp
  to:
    kind: Service
    name: welcome
    weight: 100
  wildcardPolicy: None
