apiVersion: v1
kind: Service
metadata:
  labels:
    app: welcome
  name: welcome-svc
  namespace: rh1-welcome
spec:
  ports:
  - name: 8080-tcp
    port: 8888
  - name: 8443-tcp
    port: 8443
  selector:
    deployment: welcome-rh1
