---
- name: Automate CTFD Provisioning
  hosts: all
  become: true
  vars:
    ctfd_dir: "/ctfd"
    selinux_config: "/etc/selinux/config"
    systemd_unit_file: "/etc/systemd/system/ctfd.service"
    ctfd_service_content: |
      [Unit]
      Description=CTFD Service
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/podman-compose -f /ctfd/CTFd/docker-compose.yml up
      ExecStop=/usr/local/bin/podman-compose -f /ctfd/CTFd/docker-compose.yml down
      Restart=always
      WorkingDirectory=/ctfd/CTFd
      User=root
      Group=root

      [Install]
      WantedBy=multi-user.target

  tasks:
    - name: Ensure SELinux is set to permissive temporarily
      ansible.builtin.command: setenforce 0
      ignore_errors: true

    - name: Set SELinux to permissive permanently
      ansible.builtin.lineinfile:
        path: "{{ selinux_config }}"
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'

    - name: Install required packages
      ansible.builtin.package:
        name:
          - podman
          - python3
          - python3-pip
          - git
        state: present

    - name: Install podman-compose using pip3
      ansible.builtin.pip:
        name: podman-compose
        executable: pip3

    - name: Create CTFD directory
      ansible.builtin.file:
        path: "{{ ctfd_dir }}"
        state: directory
        mode: '0755'

    - name: Clone the CTFD repository
      ansible.builtin.git:
        repo: https://github.com/CTFd/CTFd.git
        dest: "{{ ctfd_dir }}/CTFd"
        force: true

    - name: Generate CTFD secret key
      ansible.builtin.shell: head -c 64 /dev/urandom > /ctfd/.ctfd_secret_key
      args:
        creates: /ctfd/.ctfd_secret_key

    - name: Configure default container registry
      block:
        - name: Backup existing registries.conf
          ansible.builtin.copy:
            src: /etc/containers/registries.conf
            dest: /etc/containers/registries.conf.bak
            remote_src: true

        - name: Set docker.io as default registry
          ansible.builtin.lineinfile:
            path: /etc/containers/registries.conf
            regexp: '^registries =.*'
            line: 'registries = ["docker.io", "quay.io", "registry.access.redhat.com", "registry.redhat.io"]'
            insertafter: 'unqualified-search-registries ='

    - name: Run podman-compose to deploy CTFD
      ansible.builtin.command: /usr/local/bin/podman-compose up -d
      args:
        chdir: "{{ ctfd_dir }}/CTFd"

    - name: Validate CTFD deployment (HTTP check)
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
      register: http_check
      retries: 5
      delay: 10
      until: http_check.status == 200

    - name: Log deployment details
      ansible.builtin.copy:
        content: |
          Deployment log:
          Hostname: {{ ansible_fqdn }}
          CTFD Directory: {{ ctfd_dir }}
        dest: "{{ ctfd_dir }}/ctfd_deployment.log"

    - name: Deploy systemd unit file for CTFD
      ansible.builtin.copy:
        content: "{{ ctfd_service_content }}"
        dest: "{{ systemd_unit_file }}"
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start the CTFD service
      ansible.builtin.systemd:
        name: ctfd
        enabled: true
        state: started

    - name: Validate CTFD service status
      ansible.builtin.systemd:
        name: ctfd
        state: started
      register: service_status

    - name: Log service deployment status
      ansible.builtin.copy:
        content: |
          Service Deployment Status:
          Hostname: {{ ansible_fqdn }}
          CTFD Service: {{ 'Active' if service_status.status.ActiveState == 'active' else 'Inactive' }}
        dest: "{{ ctfd_dir }}/ctfd_service_status.log"
