---
- name: Deploy MachineConfig for OpenShift Master NTP Configuration
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create or update the NTP MachineConfig for masters
      community.okd.k8s:
        definition:
          apiVersion: machineconfiguration.openshift.io/v1
          kind: MachineConfig
          metadata:
            labels:
              machineconfiguration.openshift.io/role: master
            name: 50-masters-ntp-configuration
          spec:
            config:
              ignition:
                version: 3.1.0
              storage:
                files:
                - contents:
                    source: data:text/plain;charset=utf-8;base64,IyBVc2Ugc2VydmVycyBmcm9tIHRoZSBwb29sLm50cC5vcmcgcHJvamVjdAojIFRoZSBwb29sIHNlcnZlcnMgYXJlIGdlb2dyYXBoaWNhbGx5IGRpc3RyaWJ1dGVkIGZvciBvcHRpbWFsIHN5bmNocm9uaXphdGlvbi4Kc2VydmVyIDAucG9vbC5udHAub3JnIGlidXJzdApzZXJ2ZXIgMS5wb29sLm50cC5vcmcgaWJ1cnN0CnNlcnZlciAyLnBvb2wubnRwLm9yZyBpYnVyc3QKc2VydmVyIDMubGFzdmVnYXMubnRwLm9yZyBpYnVyc3QK
                  mode: 420
                  overwrite: true
                  path: /etc/ntp.conf
    - name: Create or update the NTP MachineConfig for workers
      community.okd.k8s:
        definition:
          apiVersion: machineconfiguration.openshift.io/v1
          kind: MachineConfig
          metadata:
            labels:
              machineconfiguration.openshift.io/role: worker
            name: 50-workers-ntp-configuration
          spec:
            config:
              ignition:
                version: 3.1.0
              storage:
                files:
                - contents:
                    source: data:text/plain;charset=utf-8;base64,IyBVc2Ugc2VydmVycyBmcm9tIHRoZSBwb29sLm50cC5vcmcgcHJvamVjdAojIFRoZSBwb29sIHNlcnZlcnMgYXJlIGdlb2dyYXBoaWNhbGx5IGRpc3RyaWJ1dGVkIGZvciBvcHRpbWFsIHN5bmNocm9uaXphdGlvbi4Kc2VydmVyIDAucG9vbC5udHAub3JnIGlidXJzdApzZXJ2ZXIgMS5wb29sLm50cC5vcmcgaWJ1cnN0CnNlcnZlciAyLnBvb2wubnRwLm9yZyBpYnVyc3QKc2VydmVyIDMubGFzdmVnYXMubnRwLm9yZyBpYnVyc3QK
                  mode: 420
                  overwrite: true
                  path: /etc/ntp.conf