apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-control-plane-cluster-1
  namespace: openshift-vsphere-infra
spec:
  replicas: 1  # Set to 1 replica
  selector:
    matchLabels:
      app: vsphere-infra-coredns
  template:
    metadata:
      labels:
        app: vsphere-infra-coredns
    spec:
      containers:
      - name: vsphere-infra-coredns
        image: quay.io/mpeterma/rh1_ctf/rh1-coredns:latest