---
- name: Deploy HAProxy Deployment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy HAProxy Deployment in openshift-vsphere-infra
      community.okd.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: haproxy-control-plane-cluster-1
            namespace: openshift-vsphere-infra
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: vsphere-infra-api-lb
            template:
              metadata:
                labels:
                  app: vsphere-infra-api-lb
              spec:
                containers:
                - name: vsphere-infra-api-lb
                  image: quay.io/mpeterma/rh1_ctf/rh1-haproxy:latest