---
- name: Deploy Keepalived Deployment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy keepalived Deployment in openshift-vsphere-infra
      community.okd.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: keepalived-control-plane-cluster-1
            namespace: openshift-vsphere-infra
          spec:
            replicas: 1  # Set to 1 replica
            selector:
              matchLabels:
                app: vsphere-infra-vrrp
            template:
              metadata:
                labels:
                  app: vsphere-infra-vrrp
              spec:
                containers:
                - name: vsphere-infra-vrrp
                  image: quay.io/mpeterma/rh1_ctf/rh1-keepalived:latest